language: java
git:
  depth: 1
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
    access_key_id: $ACCESSKEYID
    secret_access_key:
      secure: "$SECRETACCESSKEY"
    region: "us-east-2a"
    app: "Caboose"
    env: "caboose-env"