language: java
git:
  depth: 1
install: scripts/install_project.sh
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-east-2"
  app: "Caboose"
  env: "caboose-env"
  bucket-name: "elasticbeanstalk-us-east-2-657152641350"
  zip_file: 'target/caboose-1.0-SNAPSHOT.jar'
notifications:
  email: false