branch-defaults:
  default:
    environment: caboose-env
global:
  application_name: Caboose
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
