# Spring Properties
spring:
  application:
     name: web-service
  thymeleaf:
      cache: false       # Allow Thymeleaf templates to be reloaded at runtime
      prefix: classpath:/templates/    # Trailing / mandatory
                         # Template location for this application only

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port